<a href="https://colab.research.google.com/github/byhoson/ml_examples/blob/master/logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://towardsdatascience.com/logistic-regression-explained-and-implemented-in-python-880955306060

In [0]:
import numpy as np

In [0]:
# model settings
x_dim = 2
lr = 0.01

In [0]:
def generate_toy_data(size):
    x0 = np.random.normal(size=2*size).reshape(-1, 2) - 1
    x1 = np.random.normal(size=2*size).reshape(-1, 2) + 1.
    return np.concatenate([x0, x1]), np.concatenate([np.zeros(size), np.ones(size)]).astype(np.int)

In [84]:
# prepare the data
x,y = generate_toy_data(10)

print(a)
print(b)

[[-1.19012606 -2.22622386]
 [-2.04049405 -2.44751081]
 [-0.45409877  0.62979237]
 [-1.22362509 -0.68293164]
 [-2.4312614  -2.53874673]
 [-2.16945629 -0.75316156]
 [-0.50686355 -0.51116417]
 [-0.11469152 -1.22612155]
 [ 0.46647085 -0.95809234]
 [-1.27418237  0.67897371]
 [ 0.60397342  1.16668821]
 [ 2.11006207  0.78876538]
 [ 2.06181201  1.53727557]
 [-0.53003099  1.34142911]
 [ 0.59658391  2.10941091]
 [-0.11917394  0.24749154]
 [ 1.33739318  2.34437102]
 [-0.52182908  0.19253854]
 [ 0.67493564  0.88525717]
 [-0.09007521  1.29381909]]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [0]:
def sigmoid(z):
  return 1/(1+np.e**(-z))

In [0]:
def forward(w,b,X):
  """
    returns the prediction of a single input
    arguments:
      w -- weights of size [x_dim]
      b -- bias, a scalar
      X -- input data of size [batch, x_dim]
    returns:
      sigmoid(z) -- probability of being in class 1
  """
  z = b + np.matmul(w,X.T)
  return sigmoid(z)

In [0]:
def optimize(w,b,X,y,y_hat,lr=0.001):
  """
    optimize one step
    arguments:
      w -- weights of size [x_dim]
      b -- bias, a scalar
      X -- input data of size [batch, x_dim]
      y -- labels of size [batch]
      y_hat -- predictions of size [batch]
      lr -- learning rate(default = 0.001)
    returns:
      w -- optimized weights
      b -- optimized bias
  """
  bsize = len(y)
  # dw -- gradient of w
  # TODO: deal with the X multiplied at the end! -- need to use vector calculus
  dw = np.zeros_like(w)
  for i in range(len(dw)):
    dw[i] = -2/bsize*np.sum((y-y_hat)*y_hat*(1-y_hat)*X[:,i])
  # db = get derivative at b
  db = -2/bsize*np.sum((y-y_hat)*y_hat*(1-y_hat))
  # take a step
  w = w - lr * dw
  b = b - lr * db
  return w,b

In [0]:
def loss(y,y_hat):
  return np.sum((y-y_hat)**2)/len(y)

In [0]:
def train(w,b,x,epoch,lr=0.001):
  for _ in range(epoch):
    y_hat = forward(w,b,x)
    print(loss(y,y_hat))
    w,b = optimize(w,b,x,y,y_hat,lr=lr)
  return w,b

In [0]:
def eval(w,x):
  """
  returns the array of predicted values
  """
  pass

In [83]:
# initialize model by 0
weights = np.zeros(x_dim)
bias = 0.
print(weights, bias)
# train the model
weights, bias = train(weights,bias,x,100,lr=0.2)
weights, bias = train(weights,bias,x,100,lr=0.01)

[0. 0.] 0.0
0.25
0.22326226807798485
0.20064987984579435
0.1817753890048532
0.1660807208443218
0.15299599770299083
0.14201669289067592
0.13272649500409636
0.12479364754244164
0.11795781246872324
0.11201557803640168
0.1068076937790344
0.1022087892965728
0.0981194279362996
0.09446007924617272
0.09116657844296822
0.08818670704137942
0.08547760868737883
0.0830038249467153
0.0807357918643862
0.07864868040916098
0.07672149507146898
0.07493636757892207
0.07327799916742121
0.07173321681099723
0.07029061753281993
0.06894028130503052
0.06767353774868032
0.06648277533245706
0.06536128437212292
0.0643031270892917
0.06330302946910996
0.06235629078493682
0.06145870752388295
0.06060650911560065
0.05979630338623735
0.059025030065668324
0.058289920995623676
0.05758846593906525
0.05691838309220783
0.05627759356134258
0.05566419919583967
0.05507646327307736
0.054512793615752154
0.053971727791081114
0.05345192009795481
0.05295213009460002
0.05247121245770353
0.05200810799577164
0.05156183566597892
0.05113

In [57]:
w0 = np.array([1.,2.])
b0 = 2.
x0 = np.array([[1.,2.],[3.,4.]])
forward(w0,b0,x0)

[ 7. 13.]


array([0.99908895, 0.99999774])